### ISSUE TITLE
Implement kpt packages for all free5gc functions

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#105]
Refer to these as provided by Orange team.

[Parent](https://github.com/nephio-project/nephio/issues/104) issue. 

Also references:
[Presentation](https://drive.google.com/drive/folders/1WXxeOvkR4M_PpPIDe-HgLc-TjY9YvrMr)
Custom kpt packages: [kpt packages catalog](https://github.com/matysiaq/kpt-packages-catalog)
Improved [free5gc-operator](https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator): free5gc-operator
Reference helm charts: [Towards5gs](https://github.com/Orange-OpenSource/towards5gs-helm)

**Comment by johnbelamaric** [comment]
@matysiaq any updates here?

**Comment by matysiaq** [comment]
@johnbelamaric, the CLA on our side is already signed - we can progres on that. Right now we have the kpt packages [on my github](https://github.com/matysiaq/kpt-packages-catalog) (the ones from our E2E demo).

As agreed, free5gc NFs will be deployed on single CP cluster, so no modification is needed. I discussed with @henderiw that we could deploy UERANSIM as containers manage by K8s (co-colated with UPF), so we can reuse our existing packages with additional configuration. 
---
What need to be done is, at least:

(1) remove AMF, SMF (because those will be specialized)
(2) decompose free5gc NFs into separate packages (if needed, right now there is all-in-one kpt pkg for free5gc NFs - please comment)
(3) decompose (optional) and adjust UERANSIM kpt package (based on N2, N3 reference points of AMF, UPF)
(4) make a PR with at least initial version of kpt packages

@johnbelamaric - What do you think about that?

I'm at the vacation till 04.05, so I'm not up-to-date with community discussions and progres.

**Comment by johnbelamaric** [comment]
Sounds great @matysiaq. Please enjoy your vacation, this can be addressed when you return.

Ideally, we decompose each function into an individual package. Then, we can create the topology using the topology controller and/or packages containing PackageVariant / PackageVariantSet resources.

That said, if there is a "gang" of functions that we do not need to be able to run on different clusters, it would be fine to keep those all in one package. I think the best path forward would be to start with that, and then evolve it later as needed. So, skip your step 2, and I think your step 3, separate out AMF and SMF, and submit the rest of the functions as a single package for now. Once it's in the Nephio repo then we can all work on it more easily.

**Comment by johnbelamaric** [comment]
@johnbelamaric will look at right after the meeting

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/free5gc-packages/pull/16 has merged!
