### ISSUE TITLE
UI: Implement viewer for in-package PackageVariant resource

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#119]
Implement UI resource editors for PackageVariant.
Unit test coverage.

[Parent](https://github.com/nephio-project/nephio/issues/107) issue

**Comment by johnbelamaric** [comment]
@chander12shekhar any update here?

**Comment by chander12shekhar** [comment]
We have started working on PackageVarient viewer with below yaml format

apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: pv-1
  namespace: default
spec:
  upstream:
    repo: free5gc-packages
    package: pkg-example-amf-bp
    revision: v1
  downstream:
    repo: deployments
  packageContext:
    data:
      foo: bar
    removeKeys:
    - bar


For Unit test coverage - We will be doing later stage after discussing with Chris.
Now we will start with PackageVarient viewer, then discuss on editable item in spec.

**Comment by ganchandrasekaran** [comment]
@johnbelamaric Can you please help me with the following.. 
1, Please share us a complete CNF-package, moving forward this would be useful reference. Currently we refer to this doc for various yaml files in R1: https://docs.google.com/document/d/1wAgPO0IDyN-UqpB3twv3e-9mumck-5o3j8f74FLkKPI/edit#heading=h.29sr4bcxli5y 
2, Currently the GUI code for workshop is under here: https://github.com/GoogleContainerTools/kpt-backstage-plugins
Where will it go moving forward, will it be under Nephio repo? 
e.g. https://github.com/nephio-project/nephio/ui/kpt-backstage-plugins

**Comment by johnbelamaric** [comment]
/retitle Implement viewer for PackageVariant resource

1 - PVs are actually rarely hand-created. Instead, they will be machine generated from PackageVariantSet resources, and then stored in the cluster (not a package). So, we do not currently have packages with PVs in them directly. I will create one though (see https://github.com/nephio-project/nephio-example-packages/pull/5), for testing purposes. Since these are rarely hand-crafted, I have changed this issues to be *just* a viewer. Eventually, we will want a viewer for "in cluster" PVs, rather than just "in package" PVs - I assume the same viewer UI code can be used? @ChristopherFry?

2 - The PackageVariant and PackageVariantSet will be part of the upstream Porch UI, rather than the specific Nephio UI. So, for now these UI changes would be in the existing repository. Is there any issue with that? If there are CLA or foundation ownership issues, we can fork the code for now. kpt itself is in the process of moving to the CNCF (though that's not a sure thing, the CNCF has to accept it). So eventually that will be using the CNCF CLA.

We would like to add a separate plugin for Nephio that would be a separate menu item on the left hand side of Backstage. That would live in a repository in the nephio-project organization. Since the UI currently bundles backstage in the build, perhaps we can create a separate repo in nephio-project, and pull in just the Porch plugin. But I am not sure that's feasible in the R1 timeframe.

**Comment by johnbelamaric** [comment]
/retitle Implement viewer for in-package PackageVariant resource

**Comment by ganchandrasekaran** [comment]
Here is a Viewer implementation for PV,

![Image](https://user-images.githubusercontent.com/30624804/236828976-c2b17010-2bcf-47ca-9678-d9ad427931e7.PNG)

**Comment by ganchandrasekaran** [comment]
@johnbelamaric Currently implementing viewer for PVS.. Can you please review and merge this if sufficient? 

https://github.com/nephio-project/nephio-example-packages/pull/8

**Comment by johnbelamaric** [comment]
I think the viewer looks like mostly what we need - the PackageContext though should have a "data" and a "removeKeys" field - it looks like the contents of the data field is shown there. But it's hard to tell because it's cut off.

PackageVariant will be updated "soon" to include injectors and a KRM function pipeline, as described in the design.

**Comment by chander12shekhar** [comment]
@johnbelamaric I will change PackageContext to PackageContextData and "removeKeys" is key value pair or some other format?
as it's not present in yaml.

**Comment by johnbelamaric** [comment]
The example yaml may not have all fields. The definitions are here:

**Current Version**
- [Go](https://github.com/GoogleContainerTools/kpt/blob/main/porch/controllers/packagevariants/api/v1alpha1/packagevariant_types.go)
- [CRD](https://github.com/GoogleContainerTools/kpt/blob/main/porch/controllers/config/crd/bases/config.porch.kpt.dev_packagevariants.yaml)

**Upcoming Versions**
Two PRs add to this API:
- Injectors - https://github.com/GoogleContainerTools/kpt/pull/3939
- Pipeline - https://github.com/GoogleContainerTools/kpt/pull/3925

The API changes in both of those PRs are reflected in the design here: 

https://github.com/GoogleContainerTools/kpt/blob/main/docs/design-docs/08-package-variant.md#packagevariant-api

**Comment by ChristopherFry** [comment]
> pipeline is a complex type, it is the same as used in the Kptfile, so there is probably already some sort of viewer for it (@ChristopherFry ?).

The [getKptFunctionDescription()](https://github.com/GoogleContainerTools/kpt-backstage-plugins/blob/main/plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/kptfile.ts#L22) generates the pipeline view for the Kptfile. All you need to do to use this function is just map this over the pipeline array.

Being the pipeline only exists in the Kptfile today, it's not a shared function, but it's simple enough where we can copy it over to the PackageVariant viewer for the moment.

> Eventually, we will want a viewer for "in cluster" PVs, rather than just "in package" PVs - I assume the same viewer UI code can be used? @ChristopherFry?

Confirming the same viewers can be used for in cluster and in package resources.

**Comment by johnbelamaric** [comment]
Thanks Chris.

Ganesh, I forked the repo here: https://github.com/nephio-project/kpt-backstage-plugins

So, that repo falls under the Nephio CLA. I have asked Rado to set up Prow for that, too.

After kpt is in the CNCF, I assume there won't be a CLA issue anymore? Let's keep separate the "upstream porch" stuff (PackageVariant, PackageVariantSet) from Nephio-specific stuff (which will be a whole new panel anyway). Then, after kpt migrates to the CNCF maybe we can upstream your changes.

**Comment by johnbelamaric** [comment]
/retitle UI: Implement viewer for in-package PackageVariant resource

**Comment by chander12shekhar** [comment]
Here is a Viewer implementation for PV,
@johnbelamaric @ChristopherFry please let know if any changes are need?

![PV1](https://github.com/nephio-project/nephio/assets/9456572/cdb1064f-02ab-4ac4-87e9-8fec07fafc23)
![PV2](https://github.com/nephio-project/nephio/assets/9456572/a9d00d69-9d13-4152-9be8-3b14e16b7e34)

**Comment by johnbelamaric** [comment]
This has merged
