### ISSUE TITLE
Disable auto approve for PRs from core committers

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#130]
AT this point when there is a PR from core committers ( those who are listed in owner's file in a repo), the PR gets one approval automatically. This means just one more /lgtm will merge the PR. We need to avoid this and let all PRs have at least two approvals explicitly from team members other than  the original author. 

This needs to be enabled on all Nephio repos.

**Comment by johnbelamaric** [comment]
I don't know. I think three total approvers is excessive. But it's not something I will push for.

BTW, it's the "/approve" that is automatic, not the "/lgtm". Only one "/lgtm" is needed, plus "/approve"s that cover all the touched files.

Right now, we have a single OWNERS file per repo. But as we grow, we can create OWNERS files per directory. This allows delegation of a directory to different OWNERS than those listed in the top level file. For example, Sandeep is working on the nephio-controller-manager, which will live in its own directory in the repo. We can put an OWNERS file in there, so that he can do the approvals of changes in there, without someone in the top level OWNERS file having to approve it.

So, rather than multiple /approves for a change,  would prefer that we have the *right* /approves. I am not sure if Prow supports the idea of requiring multiple OWNERS of the same file to approve a change. @radoslawc do you know?  If we feel there is a need to multiple eyes on something, then we may have to do that via the "/lgtm" not the "/approve". But I am not sure Prow supports that either.
