### ISSUE TITLE
Develop nephio package  for workload cluster

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#168]
Develop nephio kpt package  for workload cluster.  Use the existing package in nephio-packages for reference.
This includes

--ConfigSync

**Comment by johnbelamaric** [comment]
This exists from the workshop. We need an update that works with the cluster installation package and bootstrap controller. The one that is there is specific to the workshop GitHub way.

/assign @liamfallon

**Comment by liamfallon** [comment]
This is the one to use for reference?
https://github.com/nephio-project/nephio-packages/tree/main/nephio-configsync

**Comment by johnbelamaric** [comment]
Yes, exactly. This issue is for the package that is deployed to the workload cluster via the bootstrap controller.

The overall idea is to be able to create a workload cluster and have it fully managed by Nephio, just by deploying a package. To do this w, create a "nephio workload cluster" package that is deployed to the management cluster whenever we want a new workload cluster. It contains:

1) a PackageVariant with an upstream pointing to the cluster provisioning package, and the downstream pointing to the management cluster repository.
2) a Repository resource for provisioning a repository in Gitea or another Git provider (alternatively, this could be another PackageVariant pointing to a package to do this, same as 1)
3) a Porch Repository resource configured to register the new repository with Porch
4) a PackageVariant with an upstream pointing to the configsync package (this is the package this issue is for), and downstream probably being the catalog repo or maybe a special repo just for these instances, or the new workload cluster repo (but that can be a little circular - needs more thought)

When the "nephio workload cluster" is cloned, it is renamed to match the name of the new cluster. That name is then propagated into the downstreams of the two package variants and into the repository resources. In this way, all of these different resources and the downstream packages generated are tied together.

So the flow is:
* User clones the nephio workload cluster package via the UI or CLI, naming the Draft clone as the new cluster name.
* User tweaks any config they want (for example, cluster CIDRs)
* User proposes and approves the Draft
* ConfigSync running in mgmt cluster sees the newly published package and syncs it to the management cluster, creating these resources in the mgmt cluster:
  * Repository provisioning resource
  * Porch Repository
  * Cluster PackageVariant
  * ConfigSync PackageVariant
* Repository controller running in the mgmt cluster picks up the provisioning resources and creates the new repo
* Porch picks up the porch repository resource and makes the new repo available to PackageVariants and the UI
* PackageVariant controller picks up the PV resources and clones those packages
  * User has to approve the PV-created cluster package and config sync package drafts
  * Auto-approval would be nice here, we can add that later
* Newly approved cluster provisioning package is synced by CS to the mgmt cluster, and the cluster provisioner begins its work
* Bootstrap controller waits for cluster to be available, and the CS package to be approved, and then does the `kpt live apply` of the CS package to the new cluster, to get CS up and running in the new workload cluster, pointing to the new repository.

**Comment by henderiw** [comment]
do we split the root sync from configsync main artifacts?

**Comment by johnbelamaric** [comment]
I don't think we need to, in our current inception. We deploy a single root sync per workload cluster.

For the management cluster, we should consider if we want to do it the same way, or do a package-by-package root or repo sync. The UI supports that for the mgmt cluster (same cluster Porch runs in).

**Comment by johnbelamaric** [comment]
That is, it separates the "Publish" from the "Deploy". For workload clusters, because of how we set up ConfigSync, we make Publish to Deployment Repo == Deploy. But the model actually allows the decoupling of those, so you can Publish but choose to deploy later. We simplify for R1 with 1:1 repo:cluster and can therefore simplify with Publish == Deploy. But for mgmt cluster we could consider decoupling.

**Comment by johnbelamaric** [comment]
See also this: https://github.com/nephio-project/nephio/issues/210
