### ISSUE TITLE
E2E testing : Test to scale up SMF ( Instantiating a new POD with more resources)

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#240]
Test the config changes (scaling out with the addition of a POD for example) for SMF.

**Comment by n2vo** [comment]
https://github.com/nephio-project/free5gc/pull/22

**Comment by johnbelamaric** [comment]
The test should be added to our [e2e](https://github.com/nephio-project/test-infra/tree/main/e2e/tests) as test case 009.sh.

**Comment by johnbelamaric** [comment]
@n2vo you assigned this to yourself prior to the discussion about automating it. Would you be able to do that - basically create a 009.sh in the scripts dir that does this? It would:
- pull out the existing smf package with `kpt alpha rpkg copy`
- modify the capacity
- push, propose, and approve the new package
- verify the SMF change via the k8s api server


The [001.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/001.sh) script does some of this, but with a fresh package rather than creating a new revision (ie, it uses `pull` not `copy`. With `copy`, one issue you may hit is this one: https://github.com/GoogleContainerTools/kpt/issues/3980#issuecomment-1581618700 

If so, I will prioritize figuring that out.

**Comment by johnbelamaric** [comment]
008.sh does this for UPF now, it seems to be working. I have asked @electrocucaracha to make some of the code in there more re-usable and move it to the lib/k8s.sh. Once that's done, it should be quick to write this - it will be almost identical to the 008.sh script.

**Comment by johnbelamaric** [comment]
done
