### ISSUE TITLE
Finalize repos for Nephio Packages

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#271]
Right now most of the packages are in nephio-example-packages repo. Before the release we need to make sure core Nephio packages are hosted in the right repo.

**Comment by johnbelamaric** [comment]
So, here's one thing about #258. It applies ONLY to our sandbox, not to bring-your-own-cluster. So, I think we probably want (conceptually, names can be debated)

- nephio-packages: base nephio components that apply to all installations (porch, nephio-controllers, nephio-webui, configsync, nephio-topology-controller, maybe some others?)
- nephio-demo-sandbox-packages: versions (derivatives) of the nephio-packages with any edits needed for our sandbox environment. For example, we could clone nephio-webui, and the load balancer configuration to the service. This is also where all gitea, metallb, etc. packages would live
- free5gc-packages: all the specific packages for free5gc including the operator and the individual function packages
- example-packages: maybe we want this with examples of other workloads?

**Comment by henderiw** [comment]
if you look at it I would go for 1 repo with all packages.
Now we can divide in different ways. Personally I like to split config from base SW.

E.g. we split rootsync from configsync because of this as they can be used in a decoupled matter.

SW we could split into:
1. core nephio
2. reference SW packages, like capi, metallb, resource backend, I also see free5gc here

Config would a reference configs. The fact they run on sandbox or other should not matter.

**Comment by gvbalaji** [comment]
Better to defer this after R1.

**Comment by johnbelamaric** [comment]
Here is my proposal. For past discussion on this, see also #10 .

## Conventions for Package Repositories

* Repository names are lowercase, hyphen-delimited segments that match Kubernetes naming conventions so that the Porch name for the repository match the Git name for the repository. 
* The first segment is `blueprints` or `deploy`, to indicate whether they contain DRY or WET packages.
* For deployment repositories, the second segment is the cluster name.
  * Q: Once #335 is implemented, we may have deployment repositories that are shared across clusters. So, maybe we should set a convention now that instead, the second second is `cluster` or `group`, and the third segment is the name of the cluster or group?
* For blueprint repositories the second segment depends on if the repository is expected to be consumed as an external, organizational, or team repository.
* For organizational and team blueprint repositories
  * The second segment should be `org` or `team` respectively.
  * The third section should be the team identifier for the team repositories.
  * The rest of the name should follow the same convention as for external repositories, just shifted over. 
* For external blueprint repositories (that is, repositories published by Nephio or a vendor for wide consumption), the second segment is `infra` or `nf` or `app`, indicating whether the packages in the repository are for creating infrastructure, network functions, or general purpose applications.
  * Q: Maybe we get rid of `nf` and just treat them as apps?
  * Q: Should we add a category for application config, `appconfig`?
  * Q: Should we further split infra? For example, `cloud` for things that are for provisioning the cloud layer, versus things like the vlanindex package?
* For external blueprint repositories, the third segment is vendor or other similar grouping.
* For external blueprint repositories, there may be a fourth segment that can refine the contents. For example, sometimes there are tweaks made for a particular opinionated installation. Those would have a fourth segment, indicating the opinionated installation name.

## Nephio Repositories

Based on these conventions, Nephio has the following repositories in the `nephio-project` organization.

* `blueprints-app-nephio-core` - contains packages for Nephio components themselves, including:
  * Porch
  * ConfigSync
  * Nephio Controllers
  * Nephio WebUI
* `blueprints-app-nephio-opt` - contains optional packages used across multiple opinionated installations
  * Resource Backend
  * cert-manager
  * Gitea
  * Flux Helm Controllers
* `blueprints-app-nephio-sandbox` - contains derivatives of the core and opt packages, as well as its own sandbox-specific packages
* `blueprints-app-nephio-gcp` - contains derivatives of the core and opt packages, as well as its own gcp-specific packages
* `blueprints-infra-capi` - contains packages for provisioning clusters with CAPI
* `blueprints-infra-gcp` - contains packages for provisioning infrastructure on GCP
* `blueprints-infra-openshift` - contains packages for provisioning infrastructure on OpenShift
* `blueprints-nf-free5gc` - contains the free5gc operator and basic NF packages
* `blueprints-nf-free5gc-examples` - for example architectures using free5gc
* `blueprints-nf-oai` - contains the OAI operator and basic NF packages
* `blueprints-nf-oai-examples` - for example architectures using OAI
* `blueprints-nf-mixed-examples` - for examples mixing different vendor functions

**Comment by johnbelamaric** [comment]
Based on the meeting yesterday, we will instead use a single repo with subdirectories for most of this. There may be some additional repos, but we will start with a single one and directories so we can utilize the prow tooling more easily. Porch repos can be scoped to a directory.

**Comment by johnbelamaric** [comment]
Ok, based on the meeting, here is what I am proposing, please comment on this PR:

https://github.com/nephio-project/catalog/pull/2
