### ISSUE TITLE
Gather use cases and requirements for supporting Helm charts in Nephio

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#35]
Today Helm is the most common packaging tool used by the NF vendors to package CNFs and  CSPs to deploy them. This means there is a lot of existing investment from both vendors and CSPs on Helm. 

This issue is to track the the What (requirements) and not the How (Design and implementation details). We will target only the requirements gatherings for the R1 time frame. The how part of the equation will be discussed after R1 release.

This issue should gather the following details.

- What are the main uses cases for Helm support (is it to support the existing investments Or support going forward as well)
- Priority on what aspects of Helm that needs support
-  Do customers customize the Helm charts themselves or do they just play with values file
-  In overall CNF orchestration in a CSP through their OSS/BSS systems where does it sit today.
-  Pain points with Helm 
-  Best practices 
-  What is the intended direction from both NF vendors and CSPs to move away from Helm

**Comment by ciaranjohnston** [comment]
Notes taken in today's SIG Automation discussion on this topic:

* Need to consider what versions of helm we will support - 2 or 3
** Lots of charts still around on helm 2
* helm charts can have plugins, do we need to support them?
* Do we need to support helm charts that are rendered in the running cluster? This can be problematic in terms of the current workflows
* Step back to what we are trying to achieve
** Helm files including values files can be very complex to manage. Handling hundreds of parameters requires a lot of knowledge
* Are we considering helm to protect investment, or because helm is the best tool?
** Some vendors have switched to operators and the experience is better - however CRDs are not a panacea
* How are we managing policy and closed loop? Having this sit outside of K8S (ALA ONAP) is problematic
** Can consider learnings from policy in ONAP into Nephio in a future release
* Need to consider helm as a packaging tool vs LCM tool - how can we slice and dice it and map to capabilities that are aligned with Nephio objectives
* Need strict rules on helm charts to bring them in to be supported in Nephio
* If CRDs are the end goal, we should limit support for helm to what is needed to manage the transition
** Start with the bare minimum acceptable and move to CRDs as a community
* Flux approach takes the helm charts and processes them - allows for gitops style mgt
** consider this as an approach for Nephio in the solution
** However a lot of helm charts are blurring the boundaries to infra capabilities so some changes may be required in the helm charts to support this approach
* Helm and Nephio are “diametrically opposites” - Nephio is WYSIWYM, Helm requires the files to be rendered in order to see what you will get
* Do we support helm at a particular point in time, or do we evolve with helm as it evolves - “first class” vs “transitory” for packaging and LCM.

**Comment by efiacor** [comment]
Hi guys, @johnbelamaric @tliron @henderiw 
I guess this will move to R2 in some form.
As we have already started some PoC work would it make sense to create some placeholder tickets for them?
Using flux to deploy helm?
Using the operator-sdk to deploy helm?

**Comment by henderiw** [comment]
from my perspective we need to agree on approach, I just posted something on slack that is probably important to flush out.

I paste it here as well:
Now the challenge we have is this. On one hand we want to decouple infra from NF and on the other end we want to reuse existing charts. My view is that this conflict. E.g. look at free5gc it renders the NAD. From my pov ,the NAD is an infra resource which the NF can specify req for, but the team that will define the NAD is the infra team. irrespective if the NAD comes from mgmt cluster or workload cluster i believe the role split remains the same.
So if we look at this and agree with these roles,  the existing helm charts are not reusable as is.

In this setting a flux approach as is will not work as it need to fit in the complete Nephio philosophy.

**Comment by liamfallon** [comment]
But isn't the problem here with the way that the NAD is exposed by the NF in the charts, not with Helm or Flux as a technology per se?
