### ISSUE TITLE
Add support for reading authenticated container repositories for Kptfile functions

### ISSUE THREAD

**Issue by liamfallon** [nephio-project/nephio#637]
Original issue URL: https://github.com/kptdev/kpt/issues/3434
Original issue user: https://github.com/ChristopherFry
Original issue created at: 2022-08-03T15:21:10Z
Original issue last updated at: 2023-01-26T04:47:40Z
Original issue body: Add support to allow Porch to access authenticated container repositories for Kptfile function images. Currently Porch can only pull images from public repositories where no authentication is required, or from gcr.io using workload identity.

One specific use-case, requested by the [community](https://kubernetes.slack.com/archives/C0155NSPJSZ/p1658897863761949), is to allow private function images to be pulled from [ghcr.io](http://ghcr.io/) using a GitHub Personal Access Token.

Original issue comments:

**Comment by Catalin-Stratulat-Ericsson** [comment]
To extend on from this i would like to suggest a slight extension on what is described above.

1. Firstly the resulting implementation should be able to integrate with the majority of container registry offerings not just ghcr.io examples include Jfrog Artifactory, GitLab, Harbor or any other alternatives really,

2. Secondly the proposed solution should be able to use local registries also, it is not enough to simply be able to use authenticated online repositories as for local isolated deployments this is simply not an option, the users should be able to pass in their local/online repository information and authentication means and porch should prioritize this one over its default GCR.

3. Due to point 1 above the method of authentication must be flexible to allow for multiple forms of authentication e.g. access tokens, username & password, certificates etc and perhaps integration with already existing porch security systems.
