### ISSUE TITLE
Porch: PackageRevision `metadata.uid` field is not unique

### ISSUE THREAD

**Issue by kispaljr** [nephio-project/nephio#748]
The .metadata.uid field of PackageRevisions are  simply created from  the name and revision of the package. It is not unique in the whole cluster, because it doesn't contain the name of the registry or the namespace.

Here is an example manifest fragment for a reference:
```
  apiVersion: porch.kpt.dev/v1alpha1
  kind: PackageRevision
  metadata:
    creationTimestamp: "2024-05-30T12:13:16Z"
    labels:
      kpt.dev/latest-revision: "true"
    name: dev-e93156a441afcbcc9086e70696691bfd948faf70
    namespace: default
    resourceVersion: 4dae54df58d90db0d3c45185654cf3b68cd0470a
    uid: uid:helloworld-simple:v1
  spec:
    lifecycle: Published
    packageName: helloworld-simple
    repository: dev
    revision: v1
[...]
```

This is problematic, because:
- According to [this Kubernetes doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids) the uid field should be a UUID.
- This is clearly not what the clients of our API would expect.
- This may possibly cause #725
- This may confuse the K8s garbage collection mechanism, since the uid field is also part of ownerReferences

**Comment by tliron** [comment]
We should decide what "uniqueness" means here and what it is for. It is for clients to use, but for what purposes?

Two potential approaches:

1) Treat the objects as K8s objects. So, the identifier would be derived from K8s identifiers: namespaces, GVK, and `metadata.name`. We would also add revision information.

2) Treat the objects as "real world" objects, in this case git refs for a specific git repo URL.

I am leaning on 2. The reason being is that I think clients would be interested in the "real world" object, e.g. for storing in a database or similar. So, if there are two Porch instances running, and they use different (arbitrary) namespace names, the UID would be identical if they are referring to the same git commit.

If users actually do care about the K8s facade for some reason, then it's trivial for them to generate their own UID, because they are already accessing the K8s resource via namespace, GVK, and K8s name. Thus the UID would provide an additional feature rather than just be a translation of a new one.

**Comment by kispaljr** [comment]
One clarification: if we include the revision information in the UID it will change the UID on every Update (because the revision number changes), and the will change the UID of the object during Update. Hence my comment about that above.

**Comment by kispaljr** [comment]
We can also base the UID of the PackageRevision on the UID of the corresponding PackageRev somehow, because the later is a CR managed by the kube-apiserver.

**Comment by kispaljr** [comment]
We are relying of the uniqueness of UIDs in the porch codebase at these points:
- https://github.com/nephio-project/porch/blob/2faaa8b96704d22880604b73370bb246ec5bc846/controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go#L519
- https://github.com/nephio-project/porch/blob/2faaa8b96704d22880604b73370bb246ec5bc846/controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go#L555
- https://github.com/nephio-project/porch/blob/2faaa8b96704d22880604b73370bb246ec5bc846/test/e2e/suite_logs.go#L45
